[aws]
disabled = true

[custom.blocc]
command = "blocc config show >/dev/null 2>&1 && (blocc config show | grep -A3 'deploy:' | grep -E '(context|environment):' | awk '{print $2}' | xargs) || echo 'ğŸš«'"
detect_files = ["solution.yaml"]
format = " blocc [$output]($style) "
ignore_timeout = true

[directory]
style = "blue bold"

[docker_context]
disabled = true

[git_branch]
disabled = false

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_status]
ahead = "ğŸğŸ’¨â†‘$count"
behind = "ğŸ˜°â†“$count"
conflicted = "ğŸ³"
deleted = "ğŸ—‘"
disabled = false
diverged = "ğŸ˜µâ†‘$ahead_countâ†“$behind_count"
modified = "ğŸ“"
renamed = "ğŸ‘…"
staged = "[++($count)](green)"
stashed = "ğŸ“¦"
untracked = "ğŸ¤·"
up_to_date = "âœ“"

[hostname]
disabled = true

[kubernetes]
disabled = false

[[kubernetes.contexts]]
context_alias = "LBA"
context_pattern = "k8s-login-lba-link-stacc-dev-context"
style = "bold green"

[[kubernetes.contexts]]
context_alias = "OPF"
context_pattern = "k8s-flow-login-test-1-opf-stacc-dev-context"
style = "bold green"

[[kubernetes.contexts]]
context_alias = "OPF"
context_pattern = "scc-prod-opf-01-aks-admin"
style = "bold red"

[package]
disabled = true

[username]
disabled = true
