[aws]
disabled = true

[custom.blocc]
command = "blocc-env"
detect_files = ["solution.yaml"]
format = "ğŸ§±[$output]($style) "
ignore_timeout = true

[directory]
style = "blue bold"

[docker_context]
disabled = true

[git_branch]
disabled = false

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_status]
ahead = "ğŸğŸ’¨â†‘$count"
behind = "ğŸ˜°â†“$count"
conflicted = "ğŸ³"
deleted = "ğŸ’©"
disabled = false
diverged = "ğŸ˜µâ†‘$ahead_countâ†“$behind_count"
format = "$all_status$ahead_behind "
modified = "ğŸ’©"
renamed = "ğŸ’©"
staged = "ğŸ’©"
stashed = ""
untracked = "ğŸ’©"
up_to_date = "âœ…"

[hostname]
disabled = true

[kubernetes]
disabled = false

[[kubernetes.contexts]]
context_alias = "OPF"
context_pattern = "k8s-flow-login-test-1-opf-stacc-dev-context"
style = "bold green"

[[kubernetes.contexts]]
context_alias = "OPF"
context_pattern = "scc-prod-opf-01-aks-admin"
style = "bold red"

[[kubernetes.contexts]]
context_alias = "LBA"
context_pattern = "k8s-login-lba-link-stacc-dev-context"
style = "bold green"

[[kubernetes.contexts]]
context_alias = "Intrum"
context_pattern = "intrum-stacc-dev-aks"
style = "bold green"

[package]
disabled = true

[username]
disabled = true
